CREATE VIEW [dbo].[ClaimGroupInfo]
AS
SELECT        C.CLAIM_ID, C.PAT_ID, C.VENDOR_ID, C.PROVIDER_ID, C.LOCSVC_ID, C.DIAG_CODE1, C.DIAG_CODE2, C.DIAG_CODE3, C.DIAG_CODE4, C.DIAG_CODE5, C.DIAG_CODE6, C.DIAG_CODE7, C.DIAG_CODE8, C.PRI_PROC_CODE, 
                         C.DOS, C.DATE_EXPORTED, C.DATE_POSTED, C.DATE_PROCESSED, C.DATE_RECEIVED, C.DATE_VOIDED, C.TOTAL_CHARGE, C.AMOUNT_APPLIED, C.AMOUNT_PAID, C.COPAY_AMOUNT, C.COINS_AMOUNT, 
                         C.DEDUCTIBLE_AMOUNT, C.NON_COVERED_AMOUNT, C.DIAG_CODE9, C.DIAG_CODE10, C.DIAG_CODE11, C.DIAG_CODE12, CL.CLAIM_ID AS Expr1, CL.LINE, CL.LINE_STATUS, CL.PAYOR_ID, CL.GROUP_ID, CL.PLAN_ID, 
                         CL.SPECIALTY_CODE, CL.NETWORK_FLAG, CL.REFERRAL_ID, CL.THIRD_PARTY_LINE_ID, CL.RENDERING_PROVIDER_ID, CL.EXCEPTION_CODE_01, CL.EXCEPTION_CODE_02, CL.EXCEPTION_CODE_03, 
                         CL.EXCEPTION_CODE_04, CL.EXCEPTION_CODE_05, CL.LINE_CHARGE_AMOUNT, CL.ACCEPTED_AMOUNT, CL.ADJUSTED_AMOUNT, CL.AMOUNT_PAID AS Expr3, CL.DEDUCTIBLE_APPLIED_AMOUNT, 
                         CL.NON_COVERED_AMOUNT AS Expr4, CL.UNIT_PRICE_AMOUNT, CL.UNITS, CL.PRICING_TYPE, CL.PRIMARY_PYMT_AMOUNT, CL.PROVIDER_WITHHOLD_AMOUNT, CL.SERVICE_FROM_DATE, CL.SERVICE_TO_DATE, 
                         CL.SERVICE_TYPE_CODE, CL.POS_CODE, CL.DATE_PROCESSED AS Expr5, CL.CLOSEOUT_DATE, CL.PROCEDURE_CODE, CL.MODIFIER_CODE_01, CL.MODIFIER_CODE_02, CL.MODIFIER_CODE_03, CL.MODIFIER_CODE_04, 
                         CL.BENEFIT_LVL, CL.COB, CL.EMERGENCY, CL.Export_Price, CL.Late_Interest, CL.Id, ph.GROUP_NBR, ph.PLAN_ID AS Expr10, ph.EFF_DATE, ph.EXP_DATE, dbo.GRP.GROUP_NBR AS Expr14, dbo.GRP.EFF_DATE AS Expr16, 
                         dbo.GRP.EXP_DATE AS Expr17, dbo.GRP.GROUP_NAME, dbo.GRP.WEBSITE, dbo.GRP.GRPTYPE, dbo.GRP_TYPE.DESCRIPTION, CL.PRIOR_LINE_STATUS, CL.COINS_APPLIED_AMOUNT, CL.COPAY_APPLIED_AMOUNT
FROM            dbo.HCFA_CLAIM AS C INNER JOIN
                         dbo.HCFA_LINE AS CL ON C.CLAIM_ID = CL.CLAIM_ID INNER JOIN
                         dbo.PLNHIST AS ph ON C.PAT_ID = ph.PAT_ID INNER JOIN
                         dbo.GRP ON ph.GROUP_NBR = dbo.GRP.GROUP_NBR AND C.DOS BETWEEN ph.EFF_DATE AND ph.EXP_DATE INNER JOIN
                         dbo.GRP_TYPE ON dbo.GRP.GRPTYPE = dbo.GRP_TYPE.CODE