CREATE VIEW [dbo].[LobCode]
AS
SELECT DISTINCT Convert(int,LOB.VALUE) AS LobId, MIN(LOB.SUB_CODE) AS lobname
FROM            dbo.LOCSVC_ID AS LOB INNER JOIN
                       dbo.LOCSVC AS VN ON VN.ID = LOB.LOCSVC_ID
WHERE   (LOB.CODE = 'LOB') 
    AND (GETDATE() BETWEEN LOB.EFF_DATE AND LOB.EXP_DATE)
GROUP BY LOB.VALUE