
CREATE VIEW [dbo].[ProviderAddresInformation]
AS
SELECT     PR.ID, PR.FIRST_NAME, PR.LAST_NAME, ISNULL(PR.MIDDLE_NAME, ' ') AS MIDDLE_NAME, PR.STREET1, PR.CITY, PR.STATE, PR.ZIP_CODE, PR.PHONE, PR.FAX, 
                      PID.VALUE AS Prov_License
FROM         dbo.Provider AS PR LEFT OUTER JOIN
                      dbo.ProviderId AS PID ON PID.PROVIDER_ID = PR.ID AND PID.CODE = '0B' AND GETDATE() BETWEEN PID.EFF_DATE AND PID.EXP_DATE
WHERE     (GETDATE() BETWEEN PR.EFF_DATE AND PR.EXP_DATE)