


CREATE VIEW [dbo].[ProviderLocations]
AS
SELECT DISTINCT TOP (100) PERCENT RP.ID, GP.Group_ID, GP.Product_ID, PS.LOCATION_ID, PS.PROVIDER_ID, LOCSVC.NAME, LOCSVC.Street1, LOCSVC.Street2, LOCSVC.City, LOCSVC.State, LOCSVC.Zip_Code
FROM            dbo.RPATACCT AS RP INNER JOIN
                         dbo.PLNHIST AS PH ON RP.ID = PH.PAT_ID INNER JOIN
                         dbo.Grp_Product AS GP ON PH.GROUP_NBR = GP.Group_ID INNER JOIN
                         dbo.PROV_STATUS AS PS ON PS.PROVIDER_PRODUCT = GP.Product_ID
						 INNER JOIN LOCSVC ON PS.LOCATION_ID = LOCSVC.ID
WHERE        (GETDATE() BETWEEN PH.EFF_DATE AND PH.EXP_DATE) AND (GETDATE() BETWEEN RP.EFF_DATE AND RP.EXP_DATE)