CREATE VIEW [dbo].[Vendor]
AS
SELECT     ID, TAX_ID, TAX_SUBID, TAX_TYPE, PROVIDER_ID, EFF_DATE, EXP_DATE, MAINTENANCE_USER, MAINTENANCE_ACTION, MAINTENANCE_DATE, PAYMENT_TYPE, 
                      ABA_NUMBER, ACCOUNT_NUMBER, PAY_TO
FROM         dbo.VENDORSS