CREATE TABLE [dbo].[LobLayout] (
    [Id]               INT            IDENTITY (1, 1) NOT NULL,
    [LobId]            INT            NULL,
    [ContactPhone]     NVARCHAR (50)  NULL,
    [Phone2]           NVARCHAR (50)  NULL,
    [Fax]              NVARCHAR (50)  NULL,
    [Address1]         VARCHAR (50)   NULL,
    [Address2]         VARCHAR (50)   NULL,
    [City]             VARCHAR (20)   NULL,
    [State]            VARCHAR (20)   NULL,
    [ZipCode]          VARCHAR (10)   NULL,
    [Privacy]          NVARCHAR (50)  NULL,
    [Copyright]        NVARCHAR (50)  NULL,
    [Email]            NVARCHAR (50)  NULL,
    [ImageFooter]      NVARCHAR (MAX) NULL,
    [ImageHeader]      NVARCHAR (MAX) NULL,
    [ImageAlt]         NVARCHAR (150) NULL,
    [Font]             NVARCHAR (50)  NULL,
    [FontColor]        NVARCHAR (50)  NULL,
    [BacgroundColor]   NVARCHAR (50)  NULL,
    [DateCreated]      DATETIME       NULL,
    [UserCreated]      NVARCHAR (50)  NULL,
    [DateMaintained]   DATETIME       NULL,
    [UserMaintained]   NVARCHAR (50)  NULL,
    [UrlHeader]        NVARCHAR (MAX) NULL,
    [UrlFooter]        NVARCHAR (MAX) NULL,
    [SpecialtyId]      INT            NULL,
    [ThemeColorDarker] VARCHAR (6)    NULL,
    [ThemeColorDark]   VARCHAR (6)    NULL,
    [ThemeColorSofter] VARCHAR (6)    NULL,
    [ThemeColorSoft]   VARCHAR (6)    NULL,
    CONSTRAINT [PK_LobFooter] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90)
);

