CREATE TABLE [dbo].[OnlineEligibilityRequest] (
    [Id]                UNIQUEIDENTIFIER NOT NULL,
    [UserId]            UNIQUEIDENTIFIER NULL,
    [PatientId]         INT              NULL,
    [FirstName]         NVARCHAR (50)    NULL,
    [MiddleName]        NVARCHAR (50)    NULL,
    [LastName]          NVARCHAR (50)    NULL,
    [LocationId]        INT              NULL,
    [DateOfRequest]     DATETIME         NULL,
    [DateOfServices]    DATETIME         NULL,
    [DateOfBirth]       DATETIME         NULL,
    [Gender]            NVARCHAR (1)     NULL,
    [MemberPlan]        NVARCHAR (50)    NULL,
    [MemberGroup]       NVARCHAR (50)    NULL,
    [EligibilityStatus] NVARCHAR (50)    NULL,
    [FoundStatus]       NVARCHAR (50)    NULL,
    [ZirmedMessage]     NVARCHAR (MAX)   NULL,
    [MemberId]          NVARCHAR (MAX)   NULL,
    [DependentSequence] INT              CONSTRAINT [DF__OnlineEli__Depen__7AF13DF7] DEFAULT ((0)) NOT NULL,
    [EffectiveDate]     DATETIME         NULL,
    [ExpirationDate]    DATETIME         NULL,
    [Country]           NVARCHAR (MAX)   NULL,
    [PayorId]           INT              NOT NULL,
    [StatusComment]     NVARCHAR (500)   NULL,
    [Neic]              NVARCHAR (MAX)   NULL,
    [Street1]           NVARCHAR (100)   NULL,
    [Street2]           NVARCHAR (100)   NULL,
    [City]              NVARCHAR (50)    NULL,
    [State]             NVARCHAR (50)    NULL,
    [ZipCode]           NVARCHAR (10)    NULL,
    [Phone]             NVARCHAR (50)    NULL,
    [MaintenanceUser]   NVARCHAR (50)    NULL,
    [MaintenanceDate]   DATETIME         NULL,
    [PlanId]            NVARCHAR (50)    NULL,
    [GroupId]           NVARCHAR (50)    NULL,
    [PayorInd]          NVARCHAR (1)     NULL,
    [PatRelToInsured]   NVARCHAR (50)    NULL,
    [ZElig]             VARCHAR (50)     NULL,
    [PlanSponsor]       VARCHAR (50)     NULL,
    [PlanNumber]        INT              NULL,
    [GroupName]         VARCHAR (50)     NULL,
    [GroupNumber]       INT              NULL,
    [PlanDate]          DATETIME         NULL,
    CONSTRAINT [PK_dbo.OnlineEligibilityRequest] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90)
);

