 
CREATE PROCEDURE [dbo].[GetLocationsByLobIdAndVendorId] 
	@LOBID			INT,
	@VendorID		INT
AS
BEGIN
	
	    SET NOCOUNT ON;

		SELECT DISTINCT 
			L.LOCSVC_ID,'['+CAST(LN.ID AS VARCHAR(12))+'] '+LN.Name+' - '+Street1 AS NAME
		FROM 
			LOCSVC_ID L INNER JOIN LOCSVC LN ON L.LOCSVC_ID=LN.ID
		WHERE 
			L.LOCSVC_ID IN (
			SELECT DISTINCT LS.LOCSVC_ID
			FROM VENDOR V INNER JOIN LOCSVC_ID LS ON V.TAX_ID=LS.VALUE AND LS.CODE='LTID' AND GETDATE() BETWEEN LS.EFF_DATE AND LS.EXP_DATE
			INNER JOIN LOCSVC_ID LOB ON LOB.CODE='LOB' AND LS.LOCSVC_ID=LOB.LOCSVC_ID AND GETDATE() BETWEEN LOB.EFF_DATE AND LOB.EXP_DATE
			WHERE LOB.VALUE=@LOBID AND V.ID=@VendorID  ) 
			AND GETDATE() BETWEEN L.EFF_DATE AND L.EXP_DATE
		ORDER BY
			Name
	
END

