

CREATE PROCEDURE [dbo].[GetUMAuthDetails]
	@precert_id	INT
AS
BEGIN
	
--
/******************************************************************************************************
-- WEB AUTHORIZATION REPORT
*******************************************************************************************************/

SET NOCOUNT ON

 
DECLARE @RETURN_TABLE TABLE(
	ID				INT,
	FIRST_NAME		VARCHAR(100),
	LAST_NAME		VARCHAR(100),
	SUBSCRIBER_ID	VARCHAR(100),
	DEPENDENT_SEQ	INT,
	DOB				DATETIME,
	AUTH_NO			VARCHAR(100),
	PROCESSDATE		DATETIME,
	LOCID			INT,
	LOCNAME			VARCHAR(200),
	PROVID			INT,
	PROVNAME		VARCHAR(200),
	REVIEW_STATUS	VARCHAR(100),
	STATUS			VARCHAR(100),
	PENDDESC		VARCHAR(500),
	PENDDATE		DATETIME,
	DENIEDDESC		VARCHAR(500),
	DENYDATE		DATETIME,
	AUTHEFFDATE		DATETIME,
	AUTHEXPDATE		DATETIME)

--
/*****************************************************************************************************
--  GET DETAIL DATA FOR AUTHORIZATION
******************************************************************************************************/
INSERT INTO @RETURN_TABLE
SELECT 
	P.ID, 
	PAT.FIRST_NAME, PAT.LAST_NAME, PAT.SUBSCRIBER_ID, PAT.DEPENDENT_SEQ, 
	CONVERT(VARCHAR(10),PAT.DATE_OF_BIRTH,101) AS DOB, P.AUTH_NO, CONVERT(VARCHAR(10),P.CREATED_DATE,101) AS PROCESSDATE, 
	LOC.ID AS LOCID, LOC.Name AS LOCNAME, PROV.ID AS PROVID, PROV.NAME AS PROVNAME, ISNULL(P.REVIEW_STATUS,'P') AS REVIEW_STATUS, 
	CASE WHEN P.REVIEW_STATUS='A' THEN 'Approved' WHEN P.REVIEW_STATUS='P' THEN 'Pended' WHEN P.REVIEW_STATUS='D' THEN 'Denied' ELSE 'Pended' END STATUS,
	UMP.DESCRIPTION AS PENDDESC, CONVERT(VARCHAR(10),P.Pend_Date,101) AS PENDDATE, UMD.DESCRIPTION AS DENIEDDESC, CONVERT(VARCHAR(10),P.Deny_Date,101) AS DENYDATE
	, CONVERT(VARCHAR(10),P.EFF_DATE,101) AS AUTHEFFDATE, CONVERT(VARCHAR(10),P.EXP_DATE,101) AS AUTHEXPDATE
FROM 
	precert P INNER JOIN RPATACCT PAT ON P.ACCT_ID=PAT.ID
	INNER JOIN LOCSVC LOC ON LOC.ID=P.LOCATION_ID
	INNER JOIN PROVIDER PROV ON PROV.ID=P.PROVIDER_ID
	LEFT OUTER JOIN UM_PEND_CD UMP ON UMP.CODE=P.Pend_Code
	LEFT OUTER JOIN UM_DENIAL_CD UMD ON UMD.CODE=P.Denial_Code

WHERE 
	P.ID=@precert_id

GOTO THEEXIT

             
 
SENDERROR:
GOTO THEEXIT

THEEXIT:
 
SELECT * FROM @RETURN_TABLE 
END




