

CREATE PROCEDURE [dbo].[RBACK_PROVPAYOR]
	(
	@LOB 		INT		OUTPUT,
	@PAYOR_ID 	INT		OUTPUT,
	@PROVIDER_ID 	INT 		OUTPUT,
	@REGION		VARCHAR(5)	OUTPUT,
	@GRP		INT		OUTPUT,
	@PLN		INT		OUTPUT,
	@LOCSVC		INT		OUTPUT,
	@VDATE		DATETIME	OUTPUT)
	
AS

SET NOCOUNT ON

DECLARE @L_LOB 		INT
DECLARE @L_PAYOR_ID 	INT
DECLARE @L_PROVIDER_ID	INT
DECLARE @L_REGION	VARCHAR(5)
DECLARE @L_GRP		INT
DECLARE @L_PLN		INT
DECLARE @L_LOCSVC	INT
DECLARE @L_COUNTER	INT
DECLARE @R_LOB 		VARCHAR(1)
DECLARE @R_PAYOR_ID 	VARCHAR(1)
DECLARE @R_PROVIDER_ID	VARCHAR(1)
DECLARE @R_REGION	VARCHAR(1)
DECLARE @R_GRP		VARCHAR(1)
DECLARE @R_PLN		VARCHAR(1)
DECLARE @R_LOCSVC	VARCHAR(1)
SELECT @L_COUNTER	= 1
SELECT @L_LOB 		= @LOB
SELECT @L_PAYOR_ID 	= @PAYOR_ID
SELECT @L_PROVIDER_ID 	= @PROVIDER_ID
SELECT @L_REGION 	= @REGION
SELECT @L_GRP 		= @GRP
SELECT @L_PLN 		= @PLN
SELECT @L_LOCSVC 	= @LOCSVC
WHILE EXISTS
	(SELECT  PROG_ID
	FROM RBACK_DTL (NOLOCK)
	WHERE 	PROG_ID = 1
		AND LOB=@L_LOB
		AND SEQ=@L_COUNTER)
BEGIN
	SELECT @LOB 		= 0
	SELECT @PAYOR_ID 	= 0
	SELECT @PROVIDER_ID 	= 0
	SELECT @REGION 		= '*'
	SELECT @GRP 		= 0
	SELECT @PLN 		= 0
	SELECT @LOCSVC 		= 0
	SELECT  @R_LOB 		=F1,
		@R_PROVIDER_ID	=F2,
		@R_PAYOR_ID 	=F3,
		@R_REGION	=F4,
		@R_GRP		=F5,
		@R_PLN		=F6,
		@R_LOCSVC	=F7
	FROM RBACK_DTL (NOLOCK)
	WHERE 	PROG_ID 	= 1
		AND LOB		=@L_LOB
		AND SEQ		=@L_COUNTER
	IF @R_LOB 		= 'Y' 	SELECT @LOB 		= @L_LOB
	IF @R_PROVIDER_ID 	= 'Y'	SELECT @PROVIDER_ID 	= @L_PROVIDER_ID
	IF @R_PAYOR_ID 		= 'Y' 	SELECT @PAYOR_ID 	= @L_PAYOR_ID
	IF @R_REGION 		= 'Y'	SELECT @REGION 		= @L_REGION
	IF @R_GRP 		= 'Y'	SELECT @GRP 		= @L_GRP
	IF @R_PLN 		= 'Y'	SELECT @PLN 		= @L_PLN
	IF @R_LOCSVC 		= 'Y'	SELECT @LOCSVC 		= @L_LOCSVC
	IF EXISTS
		(SELECT LOB FROM PROV_PAYOR(NOLOCK)
			WHERE 	LOB 		= @LOB
			AND	PAYOR_ID 	= @PAYOR_ID
			AND	PROVIDER_ID 	= @PROVIDER_ID
			AND 	REGION 		= @REGION
			AND	GRP_NBR 	= @GRP
			AND	PLN_NBR 	= @PLN
			AND 	LOCSVC_ID 	= @LOCSVC
			AND	@VDATE BETWEEN EFF_DATE AND EXP_DATE)
		RETURN @L_COUNTER
	ELSE
		SELECT @L_COUNTER = @L_COUNTER + 1
END
RETURN 0



