
CREATE PROCEDURE [dbo].[RBACK_CPTLOGIC]
	(
	@PAYOR 		INT 		OUTPUT,
	@REGION  	VARCHAR(5) 	OUTPUT,
	@PLAN_ID 	INT 		OUTPUT,
	@SPECIALTY	INT 		OUTPUT,
	@PROVIDER 	INT 		OUTPUT)
AS
DECLARE @L_PAYOR	INT
DECLARE @L_REGION	VARCHAR(5)
DECLARE @L_PLAN_ID 	INT
DECLARE @L_SPECIALTY	INT
DECLARE @L_PROVIDER	INT
DECLARE @L_COUNTER	INT
DECLARE @R_PAYOR	VARCHAR(1)
DECLARE @R_REGION	VARCHAR(1)
DECLARE @R_PLAN_ID		VARCHAR(1)
DECLARE @R_SPECIALTY	VARCHAR(1)
DECLARE @R_PROVIDER	VARCHAR(1)
SELECT @L_COUNTER	=1
SELECT @L_PLAN_ID		=@PLAN_ID
SELECT @L_PAYOR		=@PAYOR
SELECT @L_REGION	=@REGION
SELECT @L_SPECIALTY	=@SPECIALTY
SELECT @L_PROVIDER	=@PROVIDER
WHILE EXISTS
	(SELECT PROG_ID
		FROM RBACK_DTL(NOLOCK)
		WHERE
		PROG_ID = 36
		AND SEQ=@L_COUNTER)
BEGIN
	SELECT	@PLAN_ID	=0
	SELECT	@PAYOR		=0
	SELECT	@REGION		='*'
	SELECT	@SPECIALTY	=0
	SELECT	@PROVIDER	=0
	
	SELECT
		@R_PAYOR	=F1,
		@R_REGION	=F2,
        @R_PLAN_ID	=F3,
		@R_SPECIALTY=F4,
		@R_PROVIDER	=F5
	FROM	RBACK_DTL(NOLOCK)
	WHERE	PROG_ID		=36
		AND SEQ		=@L_COUNTER
	IF @R_PLAN_ID	='Y' SELECT @PLAN_ID 	= @L_PLAN_ID
	IF @R_PAYOR	    ='Y' SELECT @PAYOR	    = @L_PAYOR
	IF @R_REGION	='Y' SELECT @REGION	    = @L_REGION
	IF @R_SPECIALTY	='Y' SELECT @SPECIALTY	= @L_SPECIALTY
	IF @R_PROVIDER	='Y' SELECT @PROVIDER	= @L_PROVIDER
	IF EXISTS
		(SELECT PAYOR_ID FROM CPTLOGIC(NOLOCK)
			WHERE PLAN_ID	= @PLAN_ID 
			AND PROVIDER_ID = @PROVIDER
			AND SPECIALTY 	= @SPECIALTY
			AND REGION 	    = @REGION
			AND PAYOR_ID 	= @PAYOR)
		BEGIN
			RETURN @L_COUNTER
		END
	ELSE
		SELECT @L_COUNTER=@L_COUNTER + 1
END
RETURN 0



