CREATE PROCEDURE [dbo].[usp_GetAssignVendorsByLOBIDANDUserID] 
	@UserID			INT,
	@LOBID			INT
AS
BEGIN
	DECLARE @IsSuperAdmin INT
	
	SET @IsSuperAdmin=(SELECT CASE WHEN IsSuperAdmin=1 or IsSuperUser=1 THEN 1 ELSE 0 END FROM tbl_Users WHERE UserID=@UserID)
	
	IF(@IsSuperAdmin=1)
	BEGIN
		SELECT DISTINCT 
			V.ID, '['+CAST(VN.ID AS VARCHAR(12))+'] '+VN.Name+' - '+Street1 AS Name, (SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END FROM tbl_LinkUserLOBVendorLocations UL WHERE V.ID=UL.VendorID AND UserID=@UserID AND UL.LOBID=@LOBID) AS IsChecked
		FROM 
			VENDOR V INNER JOIN LOCSVC_ID LS ON V.TAX_ID=LS.VALUE AND LS.CODE='LTID' AND GETDATE() BETWEEN LS.EFF_DATE AND LS.EXP_DATE
			INNER JOIN LOCSVC_ID LOB ON LOB.CODE='LOB' AND LS.LOCSVC_ID=LOB.LOCSVC_ID AND GETDATE() BETWEEN LOB.EFF_DATE AND LOB.EXP_DATE
			INNER JOIN LOCSVC VN ON VN.ID=V.ID
		WHERE 
			LOB.VALUE=@LOBID 
		ORDER BY 
			Name
	END
	ELSE
	BEGIN
		SELECT DISTINCT 
			V.ID, '['+CAST(VN.ID AS VARCHAR(12))+'] '+VN.Name+' - '+Street1 AS Name
		FROM 
			VENDOR V INNER JOIN LOCSVC_ID LS ON V.TAX_ID=LS.VALUE AND LS.CODE='LTID' AND GETDATE() BETWEEN LS.EFF_DATE AND LS.EXP_DATE
			INNER JOIN LOCSVC_ID LOB ON LOB.CODE='LOB' AND LS.LOCSVC_ID=LOB.LOCSVC_ID AND GETDATE() BETWEEN LOB.EFF_DATE AND LOB.EXP_DATE
			INNER JOIN LOCSVC VN ON VN.ID=V.ID
		WHERE 
			LOB.VALUE=@LOBID AND V.ID IN (SELECT ULI.VendorID FROM tbl_LinkUserLOBVendorLocations ULI WHERE ULI.UserID=@UserID AND ULI.LOBID=@LOBID) 
		ORDER BY 
			Name
	END
END

