CREATE PROCEDURE [dbo].[usp_GetAssignLocationsByLOBIDVendorIDANDUserID] 
	@UserID			INT,
	@LOBID			INT,
	@VendorID		INT
AS
BEGIN
DECLARE @IsSuperAdmin INT
	
	SET @IsSuperAdmin=(SELECT CASE WHEN IsSuperAdmin=1 or IsSuperUser=1 THEN 1 ELSE 0 END FROM tbl_Users WHERE UserID=@UserID)
	
	IF(@IsSuperAdmin=1)
	BEGIN
		SELECT DISTINCT 
			L.LOCSVC_ID, '['+CAST(ID AS VARCHAR(12))+'] '+LN.Name+' - '+Street1 AS NAME, (SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END FROM tbl_LinkUserLOBVendorLocations UL WHERE L.LOCSVC_ID=UL.LocationID AND UserID=@UserID AND UL.LOBID=@LOBID AND VendorID=@VendorID) AS IsChecked
		FROM 
			LOCSVC_ID L INNER JOIN LOCSVC LN ON L.LOCSVC_ID=LN.ID
		WHERE 
			L.LOCSVC_ID IN (
			SELECT DISTINCT LS.LOCSVC_ID
			FROM VENDOR V INNER JOIN LOCSVC_ID LS ON V.TAX_ID=LS.VALUE AND LS.CODE='LTID' AND GETDATE() BETWEEN LS.EFF_DATE AND LS.EXP_DATE
			INNER JOIN LOCSVC_ID LOB ON LOB.CODE='LOB' AND LS.LOCSVC_ID=LOB.LOCSVC_ID AND GETDATE() BETWEEN LOB.EFF_DATE AND LOB.EXP_DATE
			WHERE LOB.VALUE=@LOBID AND V.ID=@VendorID  ) 
			AND GETDATE() BETWEEN L.EFF_DATE AND L.EXP_DATE
		ORDER BY
			Name
	END
	ELSE
	BEGIN
		SELECT DISTINCT 
			L.LOCSVC_ID,'['+CAST(ID AS VARCHAR(12))+'] '+LN.Name+' - '+Street1 AS NAME, (SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END FROM tbl_LinkUserRoles UR WHERE L.LOCSVC_ID=UR.LocID AND UserID=@UserID) AS IsChecked
		FROM 
			LOCSVC_ID L INNER JOIN LOCSVC LN ON L.LOCSVC_ID=LN.ID
		WHERE 
			L.LOCSVC_ID IN (
			SELECT DISTINCT LS.LOCSVC_ID
			FROM VENDOR V INNER JOIN LOCSVC_ID LS ON V.TAX_ID=LS.VALUE AND LS.CODE='LTID' AND GETDATE() BETWEEN LS.EFF_DATE AND LS.EXP_DATE
			INNER JOIN LOCSVC_ID LOB ON LOB.CODE='LOB' AND LS.LOCSVC_ID=LOB.LOCSVC_ID AND GETDATE() BETWEEN LOB.EFF_DATE AND LOB.EXP_DATE
			WHERE LOB.VALUE=@LOBID AND V.ID=@VendorID  ) 
			AND GETDATE() BETWEEN L.EFF_DATE AND L.EXP_DATE
			AND L.LOCSVC_ID IN (SELECT ULI.LocationID FROM tbl_LinkUserLOBVendorLocations ULI WHERE ULI.UserID=@UserID AND ULI.LOBID=@LOBID AND ULI.VendorID=@VendorID) 
		ORDER BY
			Name
	END
END

